allowBuilds:
  better-sqlite3: set this to true or false
  esbuild: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
minimumReleaseAgeExclude:
  - '@payloadcms/plugin-cloud-storage@3.90.1'
  - '@payloadcms/storage-s3@3.90.1'
  - '@payloadcms/translations@3.90.1'
  - '@payloadcms/ui@3.90.1'
  - '@payloadcms/admin-bar@3.90.1'
  - '@payloadcms/db-postgres@3.90.1'
  - '@payloadcms/drizzle@3.90.1'
  - '@payloadcms/graphql@3.90.1'
  - '@payloadcms/live-preview-react@3.90.1'
  - '@payloadcms/live-preview@3.90.1'
  - '@payloadcms/next@3.90.1'
  - '@payloadcms/plugin-form-builder@3.90.1'
  - '@payloadcms/plugin-nested-docs@3.90.1'
  - '@payloadcms/plugin-redirects@3.90.1'
  - '@payloadcms/plugin-search@3.90.1'
  - '@payloadcms/plugin-seo@3.90.1'
  - '@payloadcms/richtext-lexical@3.90.1'
  - payload@3.90.1
